using ObjectOrientedProgramming.Interface;

//ClassBasic.main();
//MainLatihan.main();
//Method.main();
//Constructor.main();
//ThisKeyword.main();
//PrivateModifier.main();
//Overloading.main();
//ParamsKeyword.main();
//PassByValue.main();
//PassByRefference.main();
//ParameterOpsional.main();
//StaticKeyword.main();
//ConstructorStatic.main();
//InnerClass.main();
//InheritanceBasic.main();
//HierarchyInheritance.main();
//MultipleInheritance.main();
//ProtectedModifier.main();
//BaseKeyword.main();
//MainLatihanInheritance.main();
//MethodOverride.main();
//SealedKeyword.main();
//AbstractBasic.main();
//MainPolymorphism.main();
//PolymorphismBasic.main();
//InterfaceBasic.main();

//PropertyInterface.main();
//ImplementationInterface.main();
InheritanceInterface.main();